name: Docker Image CI

on:
  push:
    branches: [ "staging" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_REPOSITORY }}:latest

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image for docker hub
      run: docker push ${{ secrets.DOCKER_REPOSITORY }}:latest
